version: "3.9"
services:
  bot-postador-link-shopee:
    build:
      context: ./bot_postador_link_shopee
    container_name: bot-postador-link-shopee-container
    env_file:
      - ./bot_postador_link_shopee/.env

  db-service-api:
    build:
      context: ./db-service_api-shopee
    container_name: db-service-api-container
    ports:
      - "7010:7010"
    env_file:
      - ./db-service_api-shopee/.env

  bot-recebedor-comprovante:
    build:
      context: ./bot_recebedor_comprovante_shopee
    container_name: bot_recebedor_comprovante_shopee-container
    env_file:
      - ./bot_recebedor_comprovante_shopee/.env
    depends_on:
      - db-service-api
